### PR TITLE
Add PrepareStatement API

### PR DESCRIPTION
**Pull request by deadok22**
See https://github.com/indeedeng/libsql/issues/12

### CODE REVIEW

**Comment by noxora** [comment]
LGTM, but need to investigate the failed check

**Comment by deadok22** [comment]
@noxora thanks for pointing this out! It seems the failure is due to Go 1.12 being used in the CI job. Bumped it to 1.16. Let's see if that helps.

**Comment by deadok22** [comment]
Yup, that was it.

**Comment by deadok22** [comment]
Released in `v1.1.0`.

**Pull request merged**
